version: "3.9"

services:
  app:
    build: .
    container_name: poke-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=aB3dE6FgH7jK8LmN9pQrStUvWxYz1234
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
